In [1]:
#Importer les librairies necessaires
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

%matplotlib inline

In [3]:
#charger votre base de données
dataset=pd.read_csv("Modified_Hand_Gesture_Recognition_Dataset.csv")
data=dataset.iloc[:,:-2].values
target=dataset.iloc[:,-2].values

In [4]:
from sklearn.model_selection import train_test_split
data_train,data_test,target_train,target_test=train_test_split(data,target,test_size=0.2,random_state=0)

In [5]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [6]:
gnb.fit(data_train,target_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
target_pred= gnb.predict(data_test)

In [8]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print('accuracy = %f' %accuracy_score(target_test,target_pred))

accuracy = 1.000000


In [9]:
#evaluer avec mean_squared_error 
from sklearn import metrics
print("Mean Squared Error:",metrics.mean_squared_error(target_test,target_pred))

Mean Squared Error: 0.0


In [10]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()

In [11]:
bnb.fit(data_train,target_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [12]:
target_pred1= bnb.predict(data_test)

In [13]:
target_pred1

array([4, 5, 0, 4, 3, 2, 4, 4, 1, 2, 5, 0, 3, 4, 0, 1, 5, 1, 4, 3, 3, 2,
       2, 2, 4, 2, 3, 5, 4, 5, 1, 3, 0, 2, 4, 3, 3, 3, 5, 0, 4, 1, 3, 0,
       3, 2, 4, 1, 0, 0, 3, 4, 3, 2, 1, 5, 3, 0, 5, 3], dtype=int64)

In [17]:
#evaluer avec mean_squared_error 
from sklearn import metrics
print("Mean Squared Error:",metrics.mean_squared_error(target_test,target_pred))

Mean Squared Error: 0.0


In [18]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print('accuracy = %f' %accuracy_score(target_test,target_pred1))

accuracy = 0.900000


In [19]:
# Input X must be non-negative So Multinomial Naïve Bayes is not useful for the prediction

from sklearn.naive_bayes import MultinomialNB
Mnb = MultinomialNB()
Mnb.fit(data_train,target_train)
target_pred2= Mnb.predict(data_test)
from sklearn import metrics
from sklearn.metrics import accuracy_score
print('accuracy = %f' %accuracy_score(target_test,target_pred2))

ValueError: Input X must be non-negative

In [20]:
print(metrics.classification_report(target_test,target_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         9
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        13
           5       1.00      1.00      1.00         7

   micro avg       1.00      1.00      1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60



In [21]:
print(metrics.confusion_matrix(target_test,target_pred))

[[ 9  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0 11  0  0]
 [ 0  0  0  0 13  0]
 [ 0  0  0  0  0  7]]
